doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            geometry:   CrEOF\Spatial\DBAL\Types\GeometryType
            point:      CrEOF\Spatial\DBAL\Types\Geometry\PointType
            polygon:    CrEOF\Spatial\DBAL\Types\Geometry\PolygonType
            linestring: CrEOF\Spatial\DBAL\Types\Geometry\LineStringType
            geometry_linestring: CrEOF\Spatial\DBAL\Types\Geometry\LineStringType
            geometry_point:      CrEOF\Spatial\DBAL\Types\Geometry\PointType
            geometry_polygon:    CrEOF\Spatial\DBAL\Types\Geometry\PolygonType
            geometry_multilinestring: CrEOF\Spatial\DBAL\Types\Geometry\MultiLineStringType
            geometry_multipoint:      CrEOF\Spatial\DBAL\Types\Geometry\MultiPointType
            geometry_multipolygon:    CrEOF\Spatial\DBAL\Types\Geometry\MultiPolygonType
            geometry_collection:    CrEOF\Spatial\DBAL\Types\Geometry\GeometryCollectionType
            geography:            CrEOF\Spatial\DBAL\Types\GeographyType
            geography_linestring: CrEOF\Spatial\DBAL\Types\Geography\LineStringType
            geography_point:      CrEOF\Spatial\DBAL\Types\Geography\PointType
            geography_polygon:    CrEOF\Spatial\DBAL\Types\Geography\PolygonType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '14'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
